#!/bin/sh
#
# AUTHOR: McUberStein3301 
#
# DATE: Tue Jul 19 2022
#
# DESC: Elvi to search Gelbooru
# elvis: gelbooru		-- Search Gelbooru (www.gelbooru.com)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search Gelbooru (www.gelbooru.com) for hentai
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://www.gelbooru.com/"
else
    formatted_args=$(echo $w3_args | sed 's/ /+/g')
    w3_browse_url "https://gelbooru.com/index.php?page=post&s=list&tags=${formatted_args}"
fi
