#!/bin/bash
PS3="What would you like to do?: "
options=("Browse Ecchi" "Browse Hentai" "Play a game" "Quit")
select opt in "${options[@]}"

	      
do
    case $opt in
	"Browse Ecchi")
	    QT_LOGGING_RULES="*=false" xdg-open /home/patrik/Pictures/LOST.DIR/DIR/Backup/A/H/BACKUP/Ecchi > /dev/null 
	    ;;
	"Browse Hentai")
	    QT_LOGGING_RULES="*=false" xdg-open /home/patrik/Pictures/LOST.DIR/DIR/Backup/A/H/BACKUP/Anime > /dev/null 
	    ;;
	"Play a game")
	    exec "/home/patrik/.scripts/game.sh" && disown
	    
	    ;;
	       
	"Quit")
	    break
	    ;;
	*) echo "invalid option $REPLY";;
    esac
done
